# libraries and settings
library("tidyverse")
library("ggplot2") #plots
library("sjstats") #test statistics
library("sjPlot")
library("sjmisc")
library("insight")
library("see")
library("ggraph")
library("parameters")
library("easystats")
library("lme4")
library("psych") ## correlation matrix
library("table1")
library("ggeffects")
library("gghighlight")
#library("naniar") # missingness
#library("Amelia")
#library("magrittr")
library("patchwork")
#library("qgraph")
library("texreg")
library("viridis")
library("ggpubr")
library("ggsci") 
library("here")
library("citr")
library("here")
#library("statsExpressions")
library("ggstatsplot")
library("ggthemes")
library("dagitty")
library("ggdag")
library("papaja")
library("rstan")
library("rstanarm")
library("tidybayes")
library("bayesplot")
library("rethinking")
library("dagitty")
library("ggdag")
rstan_options(auto_write=TRUE)
options(mc.cores=parallel::detectCores ())
theme_set(theme_few())

